# -*- coding: utf-8 -*-
"""기말프로젝트 최

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17t0CtyARneoSbnAcVtNhweSxZS8odzVY
"""

!pip install anthropic

import json
from typing import List, Dict, Any
from anthropic import Anthropic


# =====================================
# 여기다 API 키를 붙여넣으시오
# =====================================
API_KEY = "여기다 API 키를 붙여넣으시오"


client = Anthropic(
    api_key=API_KEY
)


# ------------------------------
# 긴 문서 분할
# ------------------------------
def split_text(text: str, chunk_size: int = 3000) -> List[str]:

    chunks = []

    for i in range(0, len(text), chunk_size):
        chunks.append(text[i:i + chunk_size])

    return chunks


# ------------------------------
# 프롬프트 생성
# ------------------------------
def create_summary_prompt(text: str) -> str:

    prompt = f"""
너는 강의자료를 시험 대비용 필기로 정리하는 AI이다.

반드시 JSON 형식으로만 출력하라.

출력 형식:

{{
  "title": "",
  "summary": [],
  "key_concepts": [],
  "exam_points": [],
  "review_questions": []
}}

강의자료:

{text}
"""

    return prompt


# ------------------------------
# Claude API 호출
# ------------------------------
def call_claude_api(prompt: str) -> str:

    response = client.messages.create(
        model="claude-3-5-sonnet-latest",
        max_tokens=2000,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.content[0].text


# ------------------------------
# JSON 파싱
# ------------------------------
def parse_json_response(response_text: str) -> Dict[str, Any]:

    try:
        return json.loads(response_text)

    except Exception as e:

        print("JSON 파싱 실패:", e)

        return {
            "title": "오류",
            "summary": [],
            "key_concepts": [],
            "exam_points": [],
            "review_questions": []
        }


# ------------------------------
# 단일 텍스트 요약
# ------------------------------
def summarize_text(text: str) -> Dict[str, Any]:

    prompt = create_summary_prompt(text)

    response_text = call_claude_api(prompt)

    return parse_json_response(response_text)


# ------------------------------
# 긴 문서 요약
# ------------------------------
def summarize_long_text(
    text: str,
    chunk_size: int = 3000
) -> Dict[str, Any]:

    chunks = split_text(text, chunk_size)

    final_result = {
        "title": "통합 강의 요약",
        "summary": [],
        "key_concepts": [],
        "exam_points": [],
        "review_questions": []
    }

    for idx, chunk in enumerate(chunks):

        print(f"{idx+1}/{len(chunks)} 처리 중...")

        result = summarize_text(chunk)

        final_result["summary"].extend(
            result.get("summary", [])
        )

        final_result["key_concepts"].extend(
            result.get("key_concepts", [])
        )

        final_result["exam_points"].extend(
            result.get("exam_points", [])
        )

        final_result["review_questions"].extend(
            result.get("review_questions", [])
        )

    return final_result

# ------------------------------
# 사용 예시
# ------------------------------
sample_text = """
인공지능은 인간의 지능을 모방하는 기술이다.
머신러닝은 데이터를 통해 학습한다.
딥러닝은 인공신경망을 사용한다.
"""

result = summarize_long_text(sample_text)

print(
    json.dumps(
        result,
        ensure_ascii=False,
        indent=2
    )
)